---
- hosts: all
  connection: paramiko

  tasks:
    - name: Ping hosts
      ping: ~
      tags:
        - ping

    - name: OS version information
      debug:
        msg: "Host OS: {{ ansible_system }} {{ ansible_distribution }} {{ ansible_distribution_version }}"
      tags:
        - info_os

    - name: Create user
      block:
        - name: Check mgmt_usr is defined
          block:

            - debug:
                msg: Please indicate user name in the variable 'mgmt_usr'
          always:
            - meta: end_play
          when: mgmt_usr is undefined

        - local_action:
            set_fact rand_pass="{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits,punctuation length=24') }}"
          run_once: true
          no_log: true

        - name: Create mgmt user account
          user:
            name: "{{ mgmt_usr }}"
            password: "{{ rand_pass | password_hash('sha512') }}"
            groups: "{{ mgmt_grp | default('systemd-journal') }}"
            append: yes
            shell: "/bin/bash"
            state: present

        - name: Allows user to execute commands as root
          lineinfile:
            path: "/etc/sudoers.d/{{ mgmt_usr }}"
            line: "{{ mgmt_usr }} ALL=(ALL) NOPASSWD: ALL"
            state: present
            mode: 0440
            create: yes
            validate: 'visudo -cf %s'

        - name: Generate OpenSSH key
          openssh_keypair:
            path: "{{ inventory_dir }}/{{ mgmt_usr }}"
          register: gen_openssh_key
          delegate_to: 127.0.0.1
          no_log: true
          when: ssh_pub_path is undefined

        - set_fact:
            ssh_pub_key: "{{ lookup('file', '{{ inventory_dir }}/{{ mgmt_usr }}.pub') }}"
          when: ssh_pub_path is undefined
          no_log: true

        - set_fact:
            ssh_pub_key: "{{ lookup('file', '{{ ssh_pub_path }}/{{ mgmt_usr }}.pub', errors='ignore') }}"
          when: ssh_pub_path is defined
          no_log: true

        - name: Add authorized_key took from file
          authorized_key:
            user: "{{ mgmt_usr }}"
            state: present
            key: "{{ ssh_pub_key }}"
          no_log: true
          when: ssh_pub_key is defined

        - local_action:
            debug msg="Do not forget to save your account information in a safe place! LOGIN -> {{ mgmt_usr }} & PASSWORD -> {{ rand_pass }}"
          run_once: true

        - local_action:
            debug msg="Do not forget to save the authentication keys from the <{{ inventory_dir }}> folder in a safe place! PRIVATE KEY -> {{ mgmt_usr }} & PUBLIC KEY -> {{ mgmt_usr }}.pub"
          run_once: true
          when: ssh_pub_path is undefined and ssh_pub_key is defined

        - name: Allows user to execute commands as root
          lineinfile:
            path: "{{ playbook_dir }}/logs/ansible-log.log"
            regexp: 'Do not forget to save'
            state: absent
          no_log: true
      tags:
        - create_mgmt_usr